version: 1.0.{build}
configuration: Release
cache: 
    - packages -> **\packages.config
environment:
    matrix:
    - solution_folder: GeneralHomework
      full_project_name: GeneralHomework/GeneralHomework/GeneralHomework.csproj

before_build: nuget restore %solution_folder%
build: 
    project: '%full_project_name%'
    publish_wap: true